### PR TITLE
Iccup

### PR DESCRIPTION
**Pull request by Sikian**

### CODE REVIEW

**Comment by Sikian** [comment]
Hey Vlad, please take a look if you have the time to see it makes sense with what you're working on.

Thanks!

**Comment by esiqveland** [comment]
Too late to the party I guess, but suggestion to delete the lines you have commented out. =)

Nice work on moving it to an interface!

Would be nice with some comments on the methods that are exported to help explain what their function/purpose is.

Awesome tests!

**Comment by Sikian** [comment]
Thanks Siq, I'll do so :)

**Comment by kafoso** [comment]
:+1:

**Pull request merged**
